version: '3'

services:
  web:
    build: .  # Constrói a imagem a partir do Dockerfile
    container_name: site
    restart: unless-stopped
    ports:
      - "80:80"  # Mapeia a porta 80 do host para a porta 80 do containerrm -rf .git