version: '3.8'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html  # Aponte para a pasta HTML
    ports:
      - "8080:80"
    deploy:
      restart_policy:
        condition: on-failure